name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com
      # Prevent husky
      - run: npm set-script prepare ""
      # Install packages
      - run: npm ci
      # Run build
      - run: npm run build
      # Copy files to dist dir (package.json is required)
      - run: cp ./package.json dist && cp ./README.md dist
      # Publish dist folder
      - run: npm run publish
        env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
